databases:
  - name: courregescdvdb
    plan: free
    databaseName: courregescdv
    user: courregescdv

services:
  - type: web
    plan: free
    name: courregescdv
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn courregescdv.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: courregescdvdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
